/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.NhanVien;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author @VHSkirik
 */
public class Main extends javax.swing.JFrame {

    NhanVien nhanvien;
    Color clButton;
    Color clButtonClick;

    public Main(NhanVien nhanvien) {
        initComponents();
        this.nhanvien = nhanvien;
        clButton = new Color(0, 153, 102);
        clButtonClick = new Color(0, 204, 204);
    }

    public void logOut() {
        int check = JOptionPane.showConfirmDialog(this, "Bạn muốn đăng xuất?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
        if (check == JOptionPane.YES_OPTION) {
            Login login = new Login();
            login.setVisible(true);
            this.dispose();
        }
    }

    public void hienthiQLNV() {
        vQLNhanVien qlnhanvien = new vQLNhanVien();
        pnMainContent.removeAll();
        pnMainContent.add(qlnhanvien).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnButton = new javax.swing.JPanel();
        pnButtonLogout = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnButtonNV = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnMainContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần mềm quản lý khách sạn");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnButton.setBackground(new java.awt.Color(0, 153, 102));
        pnButton.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                pnButtonAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        pnButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnButtonLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonLogoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonLogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonLogoutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnButtonLogoutMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_logout.png"))); // NOI18N
        jLabel8.setText(" ĐĂNG XUẤT");

        javax.swing.GroupLayout pnButtonLogoutLayout = new javax.swing.GroupLayout(pnButtonLogout);
        pnButtonLogout.setLayout(pnButtonLogoutLayout);
        pnButtonLogoutLayout.setHorizontalGroup(
            pnButtonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonLogoutLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnButtonLogoutLayout.setVerticalGroup(
            pnButtonLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnButtonLogoutLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnButton.add(pnButtonLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 230, 50));

        pnButtonNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnButtonNVMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnButtonNVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnButtonNVMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnButtonNVMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_nhanvien.png"))); // NOI18N
        jLabel9.setText("NHÂN VIÊN");

        javax.swing.GroupLayout pnButtonNVLayout = new javax.swing.GroupLayout(pnButtonNV);
        pnButtonNV.setLayout(pnButtonNVLayout);
        pnButtonNVLayout.setHorizontalGroup(
            pnButtonNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonNVLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnButtonNVLayout.setVerticalGroup(
            pnButtonNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnButtonNVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pnButton.add(pnButtonNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 230, 50));

        getContentPane().add(pnButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 630));

        pnMainContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnMainContentLayout = new javax.swing.GroupLayout(pnMainContent);
        pnMainContent.setLayout(pnMainContentLayout);
        pnMainContentLayout.setHorizontalGroup(
            pnMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        pnMainContentLayout.setVerticalGroup(
            pnMainContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        getContentPane().add(pnMainContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 820, 630));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnButtonAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_pnButtonAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_pnButtonAncestorAdded

    private void pnButtonLogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLogoutMouseEntered
        // TODO add your handling code here:
        pnButtonLogout.setBackground(clButtonClick);
    }//GEN-LAST:event_pnButtonLogoutMouseEntered

    private void pnButtonLogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLogoutMouseExited
        // TODO add your handling code here:
        pnButtonLogout.setBackground(clButton);
    }//GEN-LAST:event_pnButtonLogoutMouseExited

    private void pnButtonNVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonNVMouseEntered
        // TODO add your handling code here:
        pnButtonNV.setBackground(clButtonClick);
    }//GEN-LAST:event_pnButtonNVMouseEntered

    private void pnButtonNVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonNVMouseExited
        // TODO add your handling code here:
        pnButtonNV.setBackground(clButton);
    }//GEN-LAST:event_pnButtonNVMouseExited

    private void pnButtonLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLogoutMouseClicked
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_pnButtonLogoutMouseClicked

    private void pnButtonLogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonLogoutMousePressed
        // TODO add your handling code here:
        logOut();
    }//GEN-LAST:event_pnButtonLogoutMousePressed

    private void pnButtonNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonNVMouseClicked
        // TODO add your handling code here:
        hienthiQLNV();
    }//GEN-LAST:event_pnButtonNVMouseClicked

    private void pnButtonNVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnButtonNVMousePressed
        // TODO add your handling code here:
        hienthiQLNV();
    }//GEN-LAST:event_pnButtonNVMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main(new NhanVien("admin")).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnButton;
    private javax.swing.JPanel pnButtonLogout;
    private javax.swing.JPanel pnButtonNV;
    private javax.swing.JPanel pnMainContent;
    // End of variables declaration//GEN-END:variables
}
