package View;

import Controller.ConvertTime;
import Controller.LogicHoaDon;
import DAO.DAOChiTietHoaDon;
import DAO.DAOHoaDon;
import Model.ChiTietHoaDon;
import Model.HoaDon;
import java.util.ArrayList;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author @VHSkirik
 */
public class vQLHoaDon extends javax.swing.JInternalFrame {

    DefaultTableModel dtm_Hoadon;
    DefaultTableModel dtm_ChitietHD;
    String target = "";

    public vQLHoaDon() {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        dtm_Hoadon = (DefaultTableModel) tbHoaDon.getModel();
        dtm_ChitietHD = (DefaultTableModel) tbChitietHD.getModel();
        loadAllHoadon();
    }

    public vQLHoaDon(String makh) {

    }

    public void loadAllHoadon() {
        dtm_Hoadon.setRowCount(0);
        ArrayList<HoaDon> dsHoadon = DAOHoaDon.getInstance().getAll();
        for (HoaDon hd : dsHoadon) {
            String ngaythue = ConvertTime.changeToDMY(hd.getNgaythue());
            String ngaytra = ConvertTime.changeToDMY(hd.getNgaytra());
            dtm_Hoadon.addRow(new Object[]{
                hd.getMahd(),
                hd.getMakh(),
                hd.getManv(),
                hd.getMaphong(),
                hd.getGiaphong(),
                ngaythue,
                ngaytra,
                hd.getThanhtien(),
                hd.getDathanhtoan()});
        }
    }

    public void hienthiCTHD() {
        dtm_ChitietHD.setRowCount(0);
        int currentRow = tbHoaDon.getSelectedRow();
        if (currentRow != -1) {
            String mahd = dtm_Hoadon.getValueAt(currentRow, 0).toString().toLowerCase();
            ArrayList<ChiTietHoaDon> dsCTHD = DAOChiTietHoaDon.getInstance().getAll();
            for (ChiTietHoaDon cthd : dsCTHD) {
                if (cthd.getMahd().toLowerCase().equals(mahd)) {
                    dtm_ChitietHD.addRow(new Object[]{
                        cthd.getMahd(),
                        cthd.getMadichvu(),
                        cthd.getDongia(),
                        cthd.getSoluong()});
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbHoaDon = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btThemDV = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btThanhTien = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbChitietHD = new javax.swing.JTable();
        btThanhToan = new javax.swing.JButton();
        lbTongtien = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Mã KH", "Mã NV", "Mã phòng", "Giá phòng", "Ngày thuê", "Ngày trả", "Thành tiền", "Đã Trả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbHoaDon);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 850, 300));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jToolBar1.setRollover(true);

        btThemDV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThemDV.setForeground(new java.awt.Color(0, 0, 0));
        btThemDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        btThemDV.setFocusable(false);
        btThemDV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemDV.setLabel("Thêm Dịch Vụ");
        btThemDV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemDVActionPerformed(evt);
            }
        });
        jToolBar1.add(btThemDV);
        jToolBar1.add(jSeparator3);

        btSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSua.setForeground(new java.awt.Color(0, 0, 0));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_sua.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.setFocusable(false);
        btSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jToolBar1.add(btSua);

        btXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btXoa.setForeground(new java.awt.Color(0, 0, 0));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_xoa.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jToolBar1.add(btXoa);
        jToolBar1.add(jSeparator1);

        btThanhTien.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThanhTien.setForeground(new java.awt.Color(0, 0, 0));
        btThanhTien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pay.png"))); // NOI18N
        btThanhTien.setText("Thành Tiền");
        btThanhTien.setFocusable(false);
        btThanhTien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThanhTien.setIconTextGap(3);
        btThanhTien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btThanhTien);
        jToolBar1.add(jSeparator2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excel.png"))); // NOI18N
        jButton3.setText("Xuất Excel");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 390, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm hóa đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 450, 80));

        tbChitietHD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbChitietHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã dịch vụ", "Đơn giá", "Số lượng"
            }
        ));
        tbChitietHD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChitietHDMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbChitietHD);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 850, 150));

        btThanhToan.setBackground(new java.awt.Color(102, 0, 204));
        btThanhToan.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        btThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/check.png"))); // NOI18N
        btThanhToan.setText("THANH TOÁN");
        jPanel1.add(btThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 570, 230, 50));

        lbTongtien.setFont(new java.awt.Font("SF Pro Display", 0, 20)); // NOI18N
        lbTongtien.setForeground(new java.awt.Color(255, 0, 0));
        lbTongtien.setText("  Tổng tiền:");
        lbTongtien.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 51, 51), 2, true));
        jPanel1.add(lbTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 590, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        int currentRowHD = tbHoaDon.getSelectedRow();
        int currentRowCTHD = tbChitietHD.getSelectedRow();
        if (currentRowCTHD == -1 && currentRowHD == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn bản ghi cần xóa");
        } else {
            if (target.equals("CTHD")) {
                int check = JOptionPane.showConfirmDialog(this, "Xác chi tiết hóa đơn đang chọn?", "Xác Nhận", JOptionPane.YES_NO_OPTION);
                if (check == JOptionPane.YES_OPTION) {
                    String mahd = dtm_ChitietHD.getValueAt(currentRowCTHD, 0).toString();
                    String madv = dtm_ChitietHD.getValueAt(currentRowCTHD, 1).toString();
                    int rs = DAOChiTietHoaDon.getInstance().delete(mahd, madv);
                    if (rs == -1) {
                        JOptionPane.showMessageDialog(this, "Xóa thất bại");
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa Thành Công");
                        hienthiCTHD();
                    }
                }
            }
            //Xoa HD
            if (target.equals("HD")){
                int check = JOptionPane.showConfirmDialog(this, "Xóa hóa đơn và các bản Chi tiết hóa đơn của nó?","Xác Nhận",JOptionPane.YES_NO_OPTION);
                if (check == JOptionPane.YES_OPTION){
                    String mahd = dtm_Hoadon.getValueAt(currentRowHD, 0).toString();
                    int rs = LogicHoaDon.deleteAllbyMaHD(mahd);
                    if (rs == -1){
                        JOptionPane.showMessageDialog(this, "Xóa thất bại");                      
                    } else {
                        JOptionPane.showMessageDialog(this, "Xóa thành công");
                        dtm_ChitietHD.setRowCount(0);
                        loadAllHoadon();
                    }
                }
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void tbHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbHoaDonMouseClicked
        target = "HD";
        hienthiCTHD();
    }//GEN-LAST:event_tbHoaDonMouseClicked

    private void btThemDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemDVActionPerformed
        int currentRow = tbHoaDon.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showMessageDialog(this, "Hãy chọn hóa đơn cần thêm dịch vụ");
        } else {
            String mahd = dtm_Hoadon.getValueAt(currentRow, 0).toString();
            UpdateCTHD addCthd = new UpdateCTHD(this, new JFrame(), mahd);
            addCthd.setVisible(true);
        }
    }//GEN-LAST:event_btThemDVActionPerformed

    private void tbChitietHDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChitietHDMouseClicked
        target = "CTHD";
    }//GEN-LAST:event_tbChitietHDMouseClicked

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        int currentRowHoaDon = tbHoaDon.getSelectedRow();
        int currentRowCTHD = tbChitietHD.getSelectedRow();
        if (currentRowCTHD == -1 && currentRowHoaDon == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn bản ghi cần sửa");
            return;
        }
        if (target.equals("CTHD")) {
            String mahd = dtm_ChitietHD.getValueAt(currentRowCTHD, 0).toString();
            String madv = dtm_ChitietHD.getValueAt(currentRowCTHD, 1).toString();
            ChiTietHoaDon cthd = DAOChiTietHoaDon.getInstance().getByID(mahd, madv);
            UpdateCTHD updateCTHD = new UpdateCTHD(this, new JFrame(), cthd);
            updateCTHD.setVisible(true);
        }
        if (target.equals("HD")) {
            HoaDon hd = DAOHoaDon.getInstance().getByID(dtm_Hoadon.getValueAt(currentRowHoaDon, 0).toString());
            UpdateHoaDon updateHD = new UpdateHoaDon(this, new JFrame(), hd);
            updateHD.setVisible(true);
        }
    }//GEN-LAST:event_btSuaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThanhTien;
    private javax.swing.JButton btThanhToan;
    private javax.swing.JButton btThemDV;
    private javax.swing.JButton btXoa;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JTable tbChitietHD;
    private javax.swing.JTable tbHoaDon;
    // End of variables declaration//GEN-END:variables
}
