package Forms;

import DAO.DAOPhong;
import Model.Phong;
import javax.swing.JOptionPane;

/**
 *
 * @author @VHSkirik
 */
public class UpdatePhong extends javax.swing.JDialog {

    vQLPhong parent;
    String dsMaloai[];
    String maphong;

    public UpdatePhong(vQLPhong parent, java.awt.Frame frame, String dsMaloai[], String maphong) {
        super(frame, true);
        this.parent = parent;
        this.dsMaloai = dsMaloai;
        this.maphong = maphong;
        initComponents();
        hienthiCombobox();
        hienthiDuLieu();
    }

    private void hienthiCombobox() {
        for (String s : dsMaloai) {
            cbMaLoai.addItem(s);
        }
    }

    private void hienthiDuLieu() {
        //Hiển thị dữ liệu phòng cần sửa
        if (maphong != null) {
            Phong phong = DAOPhong.getInstance().getByID(maphong);
            txtMaPhong.setEnabled(false);
            lbTitle.setText("SỬA THÔNG TIN PHÒNG");
            btSubmit.setText("SỬA");
            txtMaPhong.setText(phong.getMaphong());
            txtTenPhong.setText(phong.getTenphong());
            cbMaLoai.setSelectedItem(phong.getMaloaiphong());
            if (phong.getTinhtrang() == 1) {
                chbDathue.setSelected(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        txtMaPhong = new javax.swing.JTextField();
        txtTenPhong = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btHuy = new javax.swing.JButton();
        btSubmit = new javax.swing.JButton();
        cbMaLoai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        chbDathue = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        lbTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(255, 255, 255));
        lbTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitle.setText("THÊM PHÒNG");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 60));

        txtMaPhong.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jPanel1.add(txtMaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 320, 40));

        txtTenPhong.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jPanel1.add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 320, 40));

        jLabel4.setFont(new java.awt.Font("SF Mono", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("tên phòng");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 200, -1));

        jLabel6.setFont(new java.awt.Font("SF Mono", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("mã loại");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 320, -1));

        btHuy.setBackground(new java.awt.Color(255, 0, 51));
        btHuy.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btHuy.setForeground(new java.awt.Color(255, 255, 255));
        btHuy.setText("HỦY");
        btHuy.setBorder(null);
        btHuy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });
        jPanel1.add(btHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 140, 40));

        btSubmit.setBackground(new java.awt.Color(153, 153, 255));
        btSubmit.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        btSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btSubmit.setText("THÊM");
        btSubmit.setBorder(null);
        btSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 140, 40));

        jPanel1.add(cbMaLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 320, 40));

        jLabel5.setFont(new java.awt.Font("SF Mono", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Mã phòng");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, -1));

        chbDathue.setFont(new java.awt.Font("SF Mono", 0, 14)); // NOI18N
        chbDathue.setText("Đã được thuê");
        jPanel1.add(chbDathue, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Xác nhận hủy?", "Xác Nhận", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            this.dispose();
    }//GEN-LAST:event_btHuyActionPerformed

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        String maphong = txtMaPhong.getText();
        String tenphong = txtTenPhong.getText();
        String maloaiphong = cbMaLoai.getSelectedItem().toString();
        int tinhtrang = chbDathue.isSelected() ? 1 : 0;

        //kiểm tra đầu vào
        if (maloaiphong.isBlank() || tenphong.isBlank() || maphong.isBlank()) {
            JOptionPane.showMessageDialog(this, "Kiểm tra lại thông tin");
            return;
        }

        //Thêm
        if (btSubmit.getText().equals("THÊM")) {
            //kiểm tra tồn tại
            if (DAOPhong.getInstance().getByID(maphong) != null) {
                JOptionPane.showMessageDialog(this, "Mã phòng đã tồn tại");
            } else {
                //thêm phòng từ các thông tin
                Phong phong = new Phong(maphong, tenphong, maloaiphong, tinhtrang);
                int rs = DAOPhong.getInstance().insert(phong);
                //kiểm tra kết quả sql
                if (rs == -1) {
                    JOptionPane.showMessageDialog(this, "Thêm phòng thất bại");
                } else {
                    JOptionPane.showMessageDialog(this, "Thêm phòng thành công");
                    parent.hienthiPhong();
                    this.dispose();
                }
            }
        }
        //Sửa
        if (btSubmit.getText().equals("SỬA")) {
            //Update phòng
            Phong phong = new Phong(maphong, tenphong, maloaiphong, tinhtrang);
            int rs = DAOPhong.getInstance().update(phong);
            if (rs == -1) {
                JOptionPane.showMessageDialog(this, "Sửa thông tin thất bại");
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thành công");
                parent.hienthiPhong();
                this.dispose();
            }
        }
    }//GEN-LAST:event_btSubmitActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btSubmit;
    private javax.swing.JComboBox<String> cbMaLoai;
    private javax.swing.JCheckBox chbDathue;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextField txtMaPhong;
    private javax.swing.JTextField txtTenPhong;
    // End of variables declaration//GEN-END:variables
}
