package Forms;

import DAO.DAOChiTietHoaDon;
import DAO.DAODichVu;
import DAO.DAOKhachHang;
import DAO.DAONhanVien;
import DAO.DAOPhong;
import Model.ChiTietHoaDon;
import Model.DichVu;
import Model.HoaDon;
import Model.KhachHang;
import Model.NhanVien;
import Model.Phong;
import SLogic.ConvertTime;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author @VHSkirik
 */
public class xemCTHD extends javax.swing.JDialog {

    HoaDon hd;

    public xemCTHD(java.awt.Frame parent, HoaDon hd) {
        super(parent, true);
        this.hd = hd;
        initComponents();
        loadThongTin();
    }

    private void loadThongTin() {
        //load date len txt
        KhachHang kh = DAOKhachHang.getInstance().getByID(hd.getMakh());
        NhanVien nv = DAONhanVien.getInstance().getByID(hd.getManv());
        Phong phong = DAOPhong.getInstance().getByID(hd.getMaphong());
        //settext
        txtMahd.setText(hd.getMahd());
        txtTenkh.setText(kh.getTenkh());
        txtTenNV.setText(nv.getHotenvn());
        txtTenPhong.setText(phong.getTenphong());
        txtGiaphong.setText(hd.getGiaphong() + "");
        txtNgaythue.setText(ConvertTime.changeToDMY(hd.getNgaythue()));
        txtNgaytra.setText(ConvertTime.changeToDMY(hd.getNgaytra()));
        txtTongtien.setText(hd.getThanhtien() + " VND");
        //load table        
        DefaultTableModel dtm = (DefaultTableModel) tbDichvu.getModel();
        dtm.setRowCount(0);
        //lay ten loai dich vu
        ArrayList<ChiTietHoaDon> dsCTHD = DAOChiTietHoaDon.getInstance().getAllbyMahd(hd.getMahd());
        for (ChiTietHoaDon cthd : dsCTHD) {
            DichVu dv = DAODichVu.getInstance().getByID(cthd.getMadichvu());
            dtm.addRow(new Object[]{
            dv.getTendichvu(),
            cthd.getDongia(),
            cthd.getSoluong()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDichvu = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTongtien = new javax.swing.JLabel();
        txtMahd = new javax.swing.JLabel();
        txtTenkh = new javax.swing.JLabel();
        txtTenNV = new javax.swing.JLabel();
        txtTenPhong = new javax.swing.JLabel();
        txtGiaphong = new javax.swing.JLabel();
        txtNgaythue = new javax.swing.JLabel();
        txtNgaytra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chi tiết hóa đơn");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("HÓA ĐƠN THUÊ PHÒNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 210, 33));

        jLabel2.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ngày trả:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 70, -1));

        jLabel3.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã hóa đơn:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, -1));

        jLabel4.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Tên khách hàng:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, -1));

        jLabel5.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Tên nhân viên:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 110, -1));

        jLabel6.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Tổng tiền:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 80, -1));

        jLabel7.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Giá phòng:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, -1));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Ngày thuê:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 80, -1));

        jLabel9.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tên phòng:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 80, -1));

        tbDichvu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên dịch vụ", "Giá", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tbDichvu);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 450, 150));

        jLabel10.setFont(new java.awt.Font("JetBrains Mono", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Dịch vụ:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 60, -1));

        txtTongtien.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtTongtien.setForeground(new java.awt.Color(0, 0, 0));
        txtTongtien.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        txtTongtien.setText("t");
        jPanel1.add(txtTongtien, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, 180, -1));

        txtMahd.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtMahd.setForeground(new java.awt.Color(0, 0, 0));
        txtMahd.setText("t");
        jPanel1.add(txtMahd, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 120, -1));

        txtTenkh.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtTenkh.setForeground(new java.awt.Color(0, 0, 0));
        txtTenkh.setText("t");
        jPanel1.add(txtTenkh, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, -1));

        txtTenNV.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtTenNV.setForeground(new java.awt.Color(0, 0, 0));
        txtTenNV.setText("t");
        jPanel1.add(txtTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 120, -1));

        txtTenPhong.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtTenPhong.setForeground(new java.awt.Color(0, 0, 0));
        txtTenPhong.setText("t");
        jPanel1.add(txtTenPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 120, -1));

        txtGiaphong.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtGiaphong.setForeground(new java.awt.Color(0, 0, 0));
        txtGiaphong.setText("t");
        jPanel1.add(txtGiaphong, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 120, -1));

        txtNgaythue.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtNgaythue.setForeground(new java.awt.Color(0, 0, 0));
        txtNgaythue.setText("t");
        jPanel1.add(txtNgaythue, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 120, -1));

        txtNgaytra.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        txtNgaytra.setForeground(new java.awt.Color(0, 0, 0));
        txtNgaytra.setText("t");
        jPanel1.add(txtNgaytra, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbDichvu;
    private javax.swing.JLabel txtGiaphong;
    private javax.swing.JLabel txtMahd;
    private javax.swing.JLabel txtNgaythue;
    private javax.swing.JLabel txtNgaytra;
    private javax.swing.JLabel txtTenNV;
    private javax.swing.JLabel txtTenPhong;
    private javax.swing.JLabel txtTenkh;
    private javax.swing.JLabel txtTongtien;
    // End of variables declaration//GEN-END:variables
}
