package Form;

import Logic.ConvertTime;
import Logic.LogicHoaDon;
import Logic.SearchPhong;
import DAO.DAOHoaDon;
import DAO.DAOLoaiPhong;
import Model.HoaDon;
import Model.KhachHang;
import Model.LoaiPhong;
import Model.NhanVien;
import Model.Phong;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author @VHSkirik
 */
public class AddHoaDon extends javax.swing.JInternalFrame {

    DefaultTableModel dtmLoai;
    DefaultTableModel dtmPhong;
    KhachHang kh;
    NhanVien nv;

    public AddHoaDon(KhachHang kh, NhanVien nv) {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        dtmLoai = (DefaultTableModel) tbLoai.getModel();
        dtmPhong = (DefaultTableModel) tbPhong.getModel();
        this.kh = kh;
        this.nv = nv;
        //set du lieu khi mo form
        initData();
    }

    public void initData() {
        txtMaKH.setEnabled(false);
        txtMaNV.setEnabled(false);
        txtMaKH.setText(kh.getMakh());
        txtMaNV.setText(nv.getTaikhoan());

        ArrayList<LoaiPhong> dsLoai = DAOLoaiPhong.getInstance().getAll();
        dtmLoai.setRowCount(0);
        for (LoaiPhong lp : dsLoai) {
            dtmLoai.addRow(new Object[]{
                lp.getMaloaiphong(),
                lp.getTenloaiphong(),
                lp.getGiaphong(),
                lp.getMota()});
        }
    }

    public void setDataPhong() {
        int currentRow = tbLoai.getSelectedRow();
        if (currentRow == -1) {
            
        } else {
            String maloai = dtmLoai.getValueAt(currentRow, 0).toString().toLowerCase();
            ArrayList<Phong> dsPhong = SearchPhong.getAllbyMaLoai(maloai);
            dtmPhong.setRowCount(0);
            if (btCheck.isSelected()) {
                for (Phong phong : dsPhong) {
                    if (phong.getTinhtrang() == 0) {
                        dtmPhong.addRow(new Object[]{
                            phong.getMaphong(),
                            phong.getTenphong(),
                            phong.getTinhtrang()});
                    }
                }
            } else {
                for (Phong phong : dsPhong) {
                    dtmPhong.addRow(new Object[]{
                        phong.getMaphong(),
                        phong.getTenphong(),
                        phong.getTinhtrang()});
                }
            }
        }
    }

    public void backKhachHang() {
        vQLKhachHang formKhachHang = new vQLKhachHang();
        pnMainThuePhong.removeAll();
        pnMainThuePhong.add(formKhachHang).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMainThuePhong = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhong = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLoai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMahoadon = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btHuy = new javax.swing.JButton();
        btSubmit = new javax.swing.JButton();
        btCheck = new javax.swing.JCheckBox();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMainThuePhong.setBackground(new java.awt.Color(255, 255, 255));
        pnMainThuePhong.setPreferredSize(new java.awt.Dimension(820, 630));

        tbPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Tình Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPhong);

        tbLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã LP", "Tên LP", "Giá", "Mô Tả"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbLoai);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã nhân viên");

        txtMahoadon.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mã hóa đơn");

        txtMaKH.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        txtMaKH.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mã khách hàng");

        txtMaNV.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        txtMaNV.setEnabled(false);

        btHuy.setBackground(new java.awt.Color(255, 0, 51));
        btHuy.setFont(new java.awt.Font("SF Mono", 0, 18)); // NOI18N
        btHuy.setForeground(new java.awt.Color(255, 255, 255));
        btHuy.setText("HỦY");
        btHuy.setBorder(null);
        btHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHuyActionPerformed(evt);
            }
        });

        btSubmit.setBackground(new java.awt.Color(102, 0, 204));
        btSubmit.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        btSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btSubmit.setText("SUBMIT");
        btSubmit.setBorder(null);
        btSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubmitActionPerformed(evt);
            }
        });

        btCheck.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btCheck.setForeground(new java.awt.Color(0, 0, 0));
        btCheck.setText("Phòng trống");
        btCheck.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                btCheckStateChanged(evt);
            }
        });
        btCheck.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                btCheckPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnMainThuePhongLayout = new javax.swing.GroupLayout(pnMainThuePhong);
        pnMainThuePhong.setLayout(pnMainThuePhongLayout);
        pnMainThuePhongLayout.setHorizontalGroup(
            pnMainThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainThuePhongLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnMainThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(pnMainThuePhongLayout.createSequentialGroup()
                        .addGroup(pnMainThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btCheck)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnMainThuePhongLayout.createSequentialGroup()
                                .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        pnMainThuePhongLayout.setVerticalGroup(
            pnMainThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainThuePhongLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(pnMainThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnMainThuePhongLayout.createSequentialGroup()
                        .addComponent(txtMahoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel3)
                        .addGap(0, 0, 0)
                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1)
                        .addGap(0, 0, 0)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(pnMainThuePhongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        getContentPane().add(pnMainThuePhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiMouseClicked
        // TODO add your handling code here:
        setDataPhong();
    }//GEN-LAST:event_tbLoaiMouseClicked

    private void btSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubmitActionPerformed
        // TODO add your handling code here:
        int currentRowLoai = tbLoai.getSelectedRow();
        int currentRowPhong = tbPhong.getSelectedRow();
        String mahd = txtMahoadon.getText().trim();

        if (mahd.isBlank() || currentRowLoai == -1 || currentRowPhong == -1) {
            JOptionPane.showMessageDialog(this, "Chưa điền đủ thông tin");
        } else {
            if (dtmPhong.getValueAt(currentRowPhong, 2).toString().equals("1")) {
                JOptionPane.showMessageDialog(this, "Phòng đang được thuê bởi người khác");
            } else {
                String makh = txtMaKH.getText();
                String manv = txtMaNV.getText();
                String maphong = dtmPhong.getValueAt(currentRowPhong, 0).toString();
                int giaphong = Integer.parseInt(dtmLoai.getValueAt(currentRowLoai, 2).toString());
                String ngaythue = ConvertTime.toString(new Date());

                if (DAOHoaDon.getInstance().getByID(mahd) != null) {
                    JOptionPane.showMessageDialog(this, "Mã hóa đơn đã tồn tại");
                } else {
                    HoaDon hd = new HoaDon(mahd, makh, manv, maphong, giaphong, ngaythue, null, 0, 0);
                    int i = LogicHoaDon.ThemHoaDon(hd);
                    if (i == -1){
                        JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    } else {
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        backKhachHang();
                    }
                }
            }

        }
    }//GEN-LAST:event_btSubmitActionPerformed

    private void btCheckStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_btCheckStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_btCheckStateChanged

    private void btCheckPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_btCheckPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_btCheckPropertyChange

    private void btHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHuyActionPerformed
        // TODO add your handling code here:
        int rs = JOptionPane.showConfirmDialog(this, "Hủy hóa đơn hiện tại?", "Cảnh Báo", JOptionPane.YES_NO_OPTION);
        if (rs == JOptionPane.YES_OPTION) {
            backKhachHang();
        }

    }//GEN-LAST:event_btHuyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox btCheck;
    private javax.swing.JButton btHuy;
    private javax.swing.JButton btSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnMainThuePhong;
    private javax.swing.JTable tbLoai;
    private javax.swing.JTable tbPhong;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMahoadon;
    // End of variables declaration//GEN-END:variables
}
