package Form;

import Logic.ConvertTime;
import Logic.SearchKhachHang;
import DAO.DAOHoaDon;
import DAO.DAOKhachHang;
import Model.KhachHang;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author @VHSkirik
 */
public class vQLKhachHang extends javax.swing.JInternalFrame {

    DefaultTableModel dtm;

    public vQLKhachHang() {
        initComponents();
        dtm = (DefaultTableModel) tbKhachHang.getModel();
        //Xóa title
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setupTable();
        loadDataTable();
    }

    public void setupTable() {
        //
        tbKhachHang.getColumnModel().getColumn(0).setPreferredWidth(5);
        tbKhachHang.getColumnModel().getColumn(1).setPreferredWidth(100);
        tbKhachHang.getColumnModel().getColumn(4).setPreferredWidth(5);
        tbKhachHang.getColumnModel().getColumn(5).setPreferredWidth(5);
    }

    public void loadDataTable() {
        ArrayList<KhachHang> dsKhachHang = DAOKhachHang.getInstance().getAll();
        dtm.setRowCount(0);
        for (KhachHang kh : dsKhachHang) {
            dtm.addRow(new Object[]{
                kh.getMakh(),
                kh.getTenkh(),
                ConvertTime.changeToDMY(kh.getNgaysinhkh()),
                kh.getCmt(),
                kh.getQuoctich(),
                kh.getGioitinh(),
                kh.getSodienthoai()});
        }
    }

    public void setDataTable(ArrayList<KhachHang> dsHienThi) {
        dtm.setRowCount(0);
        for (KhachHang kh : dsHienThi) {
            dtm.addRow(new Object[]{
                kh.getMakh(),
                kh.getTenkh(),
                ConvertTime.changeToDMY(kh.getNgaysinhkh()),
                kh.getCmt(),
                kh.getQuoctich(),
                kh.getGioitinh(),
                kh.getSodienthoai()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKhachHang = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btThem = new javax.swing.JButton();
        btSua = new javax.swing.JButton();
        btXoa = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btThuePhong = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jPanel2 = new javax.swing.JPanel();
        cbLoaiTK = new javax.swing.JComboBox<>();
        txtTimKiem = new javax.swing.JTextField();
        btReset = new javax.swing.JButton();

        setBorder(null);

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setPreferredSize(new java.awt.Dimension(820, 630));

        tbKhachHang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tbKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KH", "Họ Tên", "Ngày Sinh", "CMT", "Quốc Tịch", "Giới Tính", "SDT"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKhachHang);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jToolBar1.setRollover(true);

        btThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThem.setForeground(new java.awt.Color(0, 0, 0));
        btThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        btThem.setText("Thêm");
        btThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThem.setFocusable(false);
        btThem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThem.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemActionPerformed(evt);
            }
        });
        jToolBar1.add(btThem);

        btSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btSua.setForeground(new java.awt.Color(0, 0, 0));
        btSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_sua.png"))); // NOI18N
        btSua.setText("Sửa");
        btSua.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSua.setFocusable(false);
        btSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSua.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaActionPerformed(evt);
            }
        });
        jToolBar1.add(btSua);

        btXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btXoa.setForeground(new java.awt.Color(0, 0, 0));
        btXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_xoa.png"))); // NOI18N
        btXoa.setText("Xóa");
        btXoa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoa.setFocusable(false);
        btXoa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btXoa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaActionPerformed(evt);
            }
        });
        jToolBar1.add(btXoa);
        jToolBar1.add(jSeparator1);

        btThuePhong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btThuePhong.setForeground(new java.awt.Color(0, 0, 0));
        btThuePhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/test.png"))); // NOI18N
        btThuePhong.setText("Thuê Phòng");
        btThuePhong.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThuePhong.setFocusable(false);
        btThuePhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThuePhong.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThuePhong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThuePhongActionPerformed(evt);
            }
        });
        jToolBar1.add(btThuePhong);
        jToolBar1.add(jSeparator2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbLoaiTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CMT", "Họ tên" }));
        jPanel2.add(cbLoaiTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 90, 40));

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        jPanel2.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 260, 40));

        btReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_reset.png"))); // NOI18N
        btReset.setText("Reset");
        btReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btReset.setIconTextGap(10);
        btReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetActionPerformed(evt);
            }
        });
        jPanel2.add(btReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 120, 40));

        javax.swing.GroupLayout pnMainLayout = new javax.swing.GroupLayout(pnMain);
        pnMain.setLayout(pnMainLayout);
        pnMainLayout.setHorizontalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnMainLayout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnMainLayout.setVerticalGroup(
            pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnMainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, 870, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemActionPerformed
        // TODO add your handling code here:
        UpdateKH formUpdate = new UpdateKH(this, new JFrame());
        formUpdate.setVisible(true);
    }//GEN-LAST:event_btThemActionPerformed

    private void btXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaActionPerformed
        // TODO add your handling code here:
        int currentRow = tbKhachHang.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showMessageDialog(this, "Chưa bọn khách hàng cần xóa!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            int rs = JOptionPane.showConfirmDialog(this, "Xác nhận xóa", "Thông Báo", JOptionPane.YES_NO_OPTION);
            if (rs == JOptionPane.YES_OPTION) {
                String ma = dtm.getValueAt(currentRow, 0).toString();
                int kq = DAOKhachHang.getInstance().delete(ma);
                if (kq == -1) {
                    JOptionPane.showMessageDialog(this, "Xóa thất bại", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                    return;
                } else {
                    JOptionPane.showMessageDialog(this, "Xóa thành công", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
                }
                loadDataTable();
            }
        }
    }//GEN-LAST:event_btXoaActionPerformed

    private void btSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaActionPerformed
        // TODO add your handling code here:
        int currentRow = tbKhachHang.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showMessageDialog(this, "Chưa bọn khách hàng cần sửa!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
        } else {
            String ma = dtm.getValueAt(currentRow, 0).toString();
            KhachHang kh = DAOKhachHang.getInstance().getByID(ma);
            UpdateKH formUpdate = new UpdateKH(this, new JFrame(), kh);
            formUpdate.setVisible(true);
        }
    }//GEN-LAST:event_btSuaActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
        String luachon = cbLoaiTK.getSelectedItem().toString();
        String noidungTK = txtTimKiem.getText().trim().toLowerCase();
        ArrayList<KhachHang> result = new ArrayList<>();
        switch (luachon) {
            case "CMT":
                result = SearchKhachHang.getAllByCMT(noidungTK);
                break;
            case "Họ tên":
                result = SearchKhachHang.getALLByName(noidungTK);
                break;
        }
        setDataTable(result);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetActionPerformed
        txtTimKiem.setText("");
        loadDataTable();
    }//GEN-LAST:event_btResetActionPerformed

    private void tbKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhachHangMouseClicked
        
        if (evt.getClickCount() == 2) {
            String makh = dtm.getValueAt(tbKhachHang.getSelectedRow(), 0).toString();
            pnMain.removeAll();
            vQLHoaDon formLHoaDon = new vQLHoaDon(makh);
            pnMain.add(formLHoaDon);
            formLHoaDon.setVisible(true);
        }
    }//GEN-LAST:event_tbKhachHangMouseClicked

    private void btThuePhongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThuePhongActionPerformed
        // TODO add your handling code here:
        int currentRow = tbKhachHang.getSelectedRow();
        if (currentRow == -1) {
            JOptionPane.showMessageDialog(this, "Chưa chọn khách hàng nào!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        } else {
            String ma = dtm.getValueAt(currentRow, 0).toString();
            if (DAOHoaDon.getInstance().checkThanhToan(ma) == false) {
                JOptionPane.showMessageDialog(this, "Khách hàng chưa thanh toán hóa đơn cũ", "Thông báo", JOptionPane.ERROR_MESSAGE);
                return;
            }
            String ten = dtm.getValueAt(currentRow, 1).toString();
            String ns = dtm.getValueAt(currentRow, 2).toString();
            String cmt = dtm.getValueAt(currentRow, 3).toString();
            String qt = dtm.getValueAt(currentRow, 4).toString();
            String gt = dtm.getValueAt(currentRow, 5).toString();
            String sdt = dtm.getValueAt(currentRow, 6).toString();
            KhachHang kh = new KhachHang(ma, ten, ns, cmt, qt, gt, sdt);

            AddHoaDon formChoThuePhong = new AddHoaDon(kh, Main.nhanvien);
            pnMain.removeAll();
            pnMain.add(formChoThuePhong).setVisible(true);
        }
    }//GEN-LAST:event_btThuePhongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btReset;
    private javax.swing.JButton btSua;
    private javax.swing.JButton btThem;
    private javax.swing.JButton btThuePhong;
    private javax.swing.JButton btXoa;
    private javax.swing.JComboBox<String> cbLoaiTK;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel pnMain;
    private javax.swing.JTable tbKhachHang;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
