/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Form;

import DAO.DAOLoaiPhong;
import DAO.DAOPhong;
import Model.LoaiPhong;
import Model.Phong;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author @VHSkirik
 */
public class vQLPhong extends javax.swing.JInternalFrame {

    DefaultTableModel dtm_Loaiphong;
    DefaultTableModel dtm_Phong;
    ArrayList<Phong> dsPhong;

    public vQLPhong() {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        dtm_Loaiphong = (DefaultTableModel) tbLoaiphong.getModel();
        dtm_Phong = (DefaultTableModel) tbPhong.getModel();
        hienthiLoaiPhong();
        hienthiPhong();
    }

    public void resetText() {
        txtMaloai.setText("");
        txtTenLoai.setText("");
        txtGia.setText("");
        txtMota.setText("");
    }

    public boolean kiemtraText() {
        boolean rs = true;
        if (txtMaloai.getText().isBlank() || txtTenLoai.getText().isBlank() || txtGia.getText().isBlank() || txtMota.getText().isBlank()) {
            rs = false;
        } else {
            try {
                Integer.parseInt(txtGia.getText());
            } catch (Exception e) {
                rs = false;
            }
        }
        return rs;
    }

    public void hienthiLoaiPhong() {
        ArrayList<LoaiPhong> dsLoaiPhong = DAOLoaiPhong.getInstance().getAll();
        dtm_Loaiphong.setRowCount(0);
        for (LoaiPhong lp : dsLoaiPhong){
            dtm_Loaiphong.addRow(new Object[]{
            lp.getMaloaiphong(),
            lp.getTenloaiphong(),
            lp.getGiaphong(),
            lp.getMota()});
        }
    }
    
    public void hienthiPhong(){
        dsPhong = DAOPhong.getInstance().getAll();
        dtm_Phong.setRowCount(0);
        for (Phong phong : dsPhong){
            dtm_Phong.addRow(new Object[]{
            phong.getMaphong(),
            phong.getTenphong(),
            phong.getMaloaiphong(),
            phong.getTinhtrang()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPhong = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbLoaiphong = new javax.swing.JTable();
        jToolBar2 = new javax.swing.JToolBar();
        btThemLoai = new javax.swing.JButton();
        btSuaLoai = new javax.swing.JButton();
        btXoaLoai = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btResetLoai = new javax.swing.JButton();
        txtMaloai = new javax.swing.JTextField();
        txtTenLoai = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(820, 630));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Mã Loại", "Tình Trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPhong);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 850, 280));

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jToolBar1.setRollover(true);

        jButton1.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        jButton1.setText("Thêm");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton4.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_sua.png"))); // NOI18N
        jButton4.setText("Sửa");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        jButton5.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_xoa.png"))); // NOI18N
        jButton5.setText("Xóa");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);
        jToolBar1.add(jSeparator1);

        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/excel.png"))); // NOI18N
        jButton9.setText("Xuất Excel");
        jButton9.setFocusable(false);
        jButton9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton9);

        jPanel1.add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 250, 80));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tìm Kiếm Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_reset.png"))); // NOI18N
        jButton2.setText("Reset");
        jButton2.setIconTextGap(10);
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 130, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 590, 80));
        jPanel2.getAccessibleContext().setAccessibleName("Tìm Kiếm Phòng");

        tbLoaiphong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã loại", "Tên Loại", "Giá", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLoaiphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoaiphongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbLoaiphong);
        if (tbLoaiphong.getColumnModel().getColumnCount() > 0) {
            tbLoaiphong.getColumnModel().getColumn(0).setPreferredWidth(5);
            tbLoaiphong.getColumnModel().getColumn(1).setPreferredWidth(5);
            tbLoaiphong.getColumnModel().getColumn(2).setPreferredWidth(5);
            tbLoaiphong.getColumnModel().getColumn(3).setPreferredWidth(200);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 850, 150));

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng Loại Phòng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        jToolBar2.setRollover(true);

        btThemLoai.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        btThemLoai.setForeground(new java.awt.Color(0, 0, 0));
        btThemLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/plus.png"))); // NOI18N
        btThemLoai.setText("Thêm");
        btThemLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btThemLoai.setFocusable(false);
        btThemLoai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btThemLoai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThemLoaiActionPerformed(evt);
            }
        });
        jToolBar2.add(btThemLoai);

        btSuaLoai.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        btSuaLoai.setForeground(new java.awt.Color(0, 0, 0));
        btSuaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_sua.png"))); // NOI18N
        btSuaLoai.setText("Sửa");
        btSuaLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btSuaLoai.setFocusable(false);
        btSuaLoai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSuaLoai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btSuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuaLoaiActionPerformed(evt);
            }
        });
        jToolBar2.add(btSuaLoai);

        btXoaLoai.setFont(new java.awt.Font("SF Pro Display", 1, 16)); // NOI18N
        btXoaLoai.setForeground(new java.awt.Color(0, 0, 0));
        btXoaLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_xoa.png"))); // NOI18N
        btXoaLoai.setText("Xóa");
        btXoaLoai.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btXoaLoai.setFocusable(false);
        btXoaLoai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btXoaLoai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXoaLoaiActionPerformed(evt);
            }
        });
        jToolBar2.add(btXoaLoai);
        jToolBar2.add(jSeparator2);

        btResetLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btResetLoai.setForeground(new java.awt.Color(0, 0, 0));
        btResetLoai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icon_reset.png"))); // NOI18N
        btResetLoai.setText("Reset");
        btResetLoai.setFocusable(false);
        btResetLoai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btResetLoai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btResetLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btResetLoaiActionPerformed(evt);
            }
        });
        jToolBar2.add(btResetLoai);

        jPanel1.add(jToolBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 80));

        txtMaloai.setNextFocusableComponent(txtTenLoai);
        txtMaloai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMaloaiKeyPressed(evt);
            }
        });
        jPanel1.add(txtMaloai, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 180, -1));
        jPanel1.add(txtTenLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 40, 180, -1));

        txtGia.setNextFocusableComponent(txtMota);
        jPanel1.add(txtGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 180, -1));

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane3.setViewportView(txtMota);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 350, 70));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Mã loại");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Tên loại");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 50, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Mô tả");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 50, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Giá");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 30, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXoaLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btXoaLoaiActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        JOptionPane.showMessageDialog(this, "Tính năng chưa hoàn thiện");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btResetLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btResetLoaiActionPerformed
        resetText();
        txtMaloai.requestFocus();
    }//GEN-LAST:event_btResetLoaiActionPerformed

    private void btThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThemLoaiActionPerformed
        //kiểm tra đầu vào
        if (kiemtraText() == false) {
            JOptionPane.showMessageDialog(this, "Kiểm tra lại thông tin");
        } else {
            //Xác nhận thêm
            int rs = JOptionPane.showConfirmDialog(this, "Thêm bản ghi hiện tại?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (rs == JOptionPane.YES_OPTION) {
                //Kiem tra ton tai
                String maloaiphong = txtMaloai.getText();
                if (DAOLoaiPhong.getInstance().getByID(maloaiphong) != null) {
                    JOptionPane.showMessageDialog(this, "Loại phòng đã tồn tại");
                } else {
                    //Thực hiện thêm
                    String tenloaiphong = txtTenLoai.getText();
                    int giaphong = Integer.parseInt(txtGia.getText());
                    String mota = txtMota.getText();
                    LoaiPhong lp = new LoaiPhong(maloaiphong, tenloaiphong, giaphong, mota);
                    int kqThem = DAOLoaiPhong.getInstance().insert(lp);
                    //Kiểm tra kết quả thêm
                    if (kqThem == -1) {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại");
                    } else {
                        //thông báo và làm mới danh sách
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        resetText();
                        hienthiLoaiPhong();
                    }
                }
            }
        }

    }//GEN-LAST:event_btThemLoaiActionPerformed

    private void btSuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuaLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btSuaLoaiActionPerformed

    private void tbLoaiphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiphongMouseClicked
        
    }//GEN-LAST:event_tbLoaiphongMouseClicked

    private void txtMaloaiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaloaiKeyPressed

    }//GEN-LAST:event_txtMaloaiKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btResetLoai;
    private javax.swing.JButton btSuaLoai;
    private javax.swing.JButton btThemLoai;
    private javax.swing.JButton btXoaLoai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JTable tbLoaiphong;
    private javax.swing.JTable tbPhong;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaloai;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtTenLoai;
    // End of variables declaration//GEN-END:variables
}
